"""
Test Case Formatter
Formats and validates test case output
"""

from typing import Optional
import re


class TestCaseFormatter:
    """Formats and structures test case output"""

    @staticmethod
    def format_as_markdown(test_cases: str) -> str:
        """
        Format test cases as Markdown
        
        Args:
            test_cases: Raw test case text
            
        Returns:
            Formatted Markdown string
        """
        if not test_cases:
            return ""

        # Add markdown header if not present
        if not test_cases.strip().startswith("#"):
            formatted = "# Generated Test Cases\n\n"
        else:
            formatted = ""

        formatted += test_cases

        # Ensure proper spacing
        formatted = formatted.replace("\n\n\n", "\n\n")
        
        return formatted

    @staticmethod
    def extract_table_from_response(response: str) -> Optional[str]:
        """
        Extract table format from LLM response
        
        Args:
            response: LLM generated text
            
        Returns:
            Extracted table or original text
        """
        # Look for markdown table format
        if "|" in response:
            lines = response.split("\n")
            table_lines = []
            in_table = False
            
            for line in lines:
                if "|" in line:
                    if not in_table:
                        in_table = True
                    table_lines.append(line)
                elif in_table and line.strip():
                    in_table = False
                    
            if table_lines:
                return "\n".join(table_lines)
        
        return response

    @staticmethod
    def clean_output(text: str) -> str:
        """
        Clean LLM output
        
        Args:
            text: Raw LLM output
            
        Returns:
            Cleaned text
        """
        if not text:
            return ""
        
        # Remove common LLM artifacts
        text = text.strip()
        
        # Remove markdown code blocks if wrapping the content
        if text.startswith("```"):
            text = re.sub(r"^```.*?\n", "", text)
            text = re.sub(r"\n```$", "", text)
        
        # Remove extra whitespace
        text = re.sub(r"\n\n+", "\n\n", text)
        
        return text

    @staticmethod
    def validate_test_cases(test_cases: str) -> tuple[bool, str]:
        """
        Validate test case format
        
        Args:
            test_cases: Test cases to validate
            
        Returns:
            Tuple of (is_valid, message)
        """
        if not test_cases:
            return False, "Test cases are empty"
        
        if len(test_cases) < 50:
            return False, "Test cases seem too short"
        
        # Check for table structure
        if "|" not in test_cases:
            return False, "Test cases don't appear to be in table format"
        
        return True, "Test cases appear valid"

    @staticmethod
    def count_test_cases(test_cases: str) -> int:
        """
        Count number of test cases in output
        
        Args:
            test_cases: Test case text
            
        Returns:
            Approximate number of test cases
        """
        # Count table rows (excluding header)
        if "|" in test_cases:
            lines = test_cases.split("\n")
            count = sum(1 for line in lines if "|" in line and not line.startswith("|---"))
            return max(0, count - 2)  # Subtract header rows
        
        # Count by "Test Case" mentions
        return test_cases.count("Test Case")

    @staticmethod
    def export_as_markdown(test_cases: str, issue_key: str = "", filename: Optional[str] = None) -> str:
        """
        Export test cases as complete markdown document
        
        Args:
            test_cases: Test cases content
            issue_key: Jira issue key for context
            filename: Optional filename for the export
            
        Returns:
            Complete markdown document
        """
        timestamp_import = "from datetime import datetime\ntoday = datetime.now().strftime('%Y-%m-%d')"
        
        markdown = f"""# Test Cases for {issue_key}

**Generated:** {TestCaseFormatter._get_timestamp()}

## Overview
This document contains comprehensive QA test cases generated for the Jira issue **{issue_key}**.

---

## Test Cases

{test_cases}

---

## Statistics
- **Total Test Cases:** {TestCaseFormatter.count_test_cases(test_cases)}
- **Format:** Markdown Table

---

*Generated by Jira AI Test Case Generator*
"""
        
        return markdown

    @staticmethod
    def _get_timestamp() -> str:
        """Get current timestamp"""
        from datetime import datetime
        return datetime.now().strftime('%Y-%m-%d %H:%M:%S')


def get_test_case_formatter() -> TestCaseFormatter:
    """Factory function to get formatter instance"""
    return TestCaseFormatter()
